### ISSUE TITLE
implement Redux on current project

### ISSUE THREAD

**Issue by Wisdom132** [coinratecap/Frontend#23]

**Comment by Wisdom132** [comment]
Hello bro, you can start working on this....and when you are working also try to remove anything `creative time` on the template.

**Comment by Paul-Taiwo** [comment]
Alright. Noted.

**Comment by Paul-Taiwo** [comment]
@Wisdom132 I think this Issue was meant for coinratecap admin

**Comment by Wisdom132** [comment]
oh...thanks for the correction
